version: '3.8'
services:
  php-apache-environment:
    image: novansandi/php-uas
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 80:80
    networks:
      - backend
  
  db: 
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tokoonline
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./tokoonline.sql:/docker-entrypoint-intdb.d/tokoonline.sql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/24